apiVersion: v1
kind: Namespace
metadata:
  name: backend-space

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoughtcache-backend
  namespace: backend-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thoughtcache-backend
  template:
    metadata:
      labels:
        app: thoughtcache-backend
    spec:
      containers:
      - name: backend-image
        image: manikprakash/thoughtcache-backend:v1
        env:
        - name: PORT 
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: db-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        - name: JWT_EXPIRES_IN
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-expires-in
        - name: CORS_ORIGIN
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: cors-origin
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: thoughtcache-backend-service
  namespace: backend-space
spec:
  selector:
    app: thoughtcache-backend
  ports:
  - protocol: TCP 
    port: 3000
    targetPort: 3000
  type: ClusterIP
