apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thoughtcache-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thoughtcache-frontend-service
            namespace: frontend-space
            port:
              number: 80